# Generated by Django 2.1.7 on 2019-06-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190624_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='post_image',
            new_name='book_image',
        ),
    ]
